### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by bosit777** [alashow/datmusic-api#100]
There was installation guide in this repo, now i cant find it. Can you give a link if it exist now?

**Comment by alashow** [comment]
https://gist.github.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c was the old instructions. I removed it from readme because it's not that useful anymore and doesn't include deemix-py api deployment https://gist.github.com/alashow/15978818a82cb4a85e765dc348ce463e
