### ISSUE TITLE
error installation on ubuntu

### ISSUE THREAD

**Issue by mughu-id** [alashow/datmusic-api#12]
http://prntscr.com/erydvb

can you provide more specific installation ? thank you

**Comment by alashow** [comment]
See #9

 There is a gist for installation on ubuntu.

**Comment by mughu-id** [comment]
i was followed the instruction but i had a blank page with "No input file specified" .

http://prntscr.com/es74x2

**Comment by alashow** [comment]
Did you configure nginx as instructed in the gist?

**Comment by mughu-id** [comment]
i'm using apache . and i was changed Virtual Host with following the instruction .

**Comment by mughu-id** [comment]
i was changed into nginx , but now i have problem with 404 Not Found

this my .conf settings

###############################################################################
# DO NOT EDIT THIS FILE.
#
# Your changes to this file will be overwritten by ServerPilot.
#
# For information on how to customize nginx settings, see
# https://serverpilot.io/community/articles/customize-nginx-settings.html
###############################################################################

server {
    listen       80;
    listen       [::]:80;
    server_name
        server-vkmp3
        vkmp3.tk
        www.vkmp3.tk
      ;
    root   /srv/users/serverpilot/apps/vkmp3/public/current/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    index index.php index.html index.htm;

    }location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    access_log  /srv/users/serverpilot/log/vkmp3/vkmp3_nginx.access.log  main;
    error_log  /srv/users/serverpilot/log/vkmp3/vkmp3_nginx.error.log;

    proxy_set_header    Host              $host;
    proxy_set_header    X-Real-IP         $remote_addr;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;

}

**Comment by alashow** [comment]
Does `/srv/users/serverpilot/apps/vkmp3/public/current/public` folder exists and readable?

**Comment by mughu-id** [comment]
it was exists and readable .

http://prntscr.com/es7p1l

**Comment by alashow** [comment]
See /srv/users/serverpilot/log/vkmp3/vkmp3_nginx.error.log for error logs, to see which directory nginx hits.

**Comment by mughu-id** [comment]
2017/04/04 08:01:34 [crit] 9055#0: *13 connect() to unix:/var/run/php/php7.1-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 36.79.160.53, server: server-vkmp3, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "vkmp3.tk"

2017/04/04 08:03:53 [crit] 9118#0: *5 connect() to unix:/srv/users/SYSUSER/run/APPNAME.php-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 36.79.160.53, server: server-vkmp3, request: "GET /search?q=ungu HTTP/1.1", upstream: "fastcgi://unix:/srv/users/SYSUSER/run/APPNAME.php-fpm$

**Comment by alashow** [comment]
It says `/var/run/php/php7.1-fpm.sock` doesn't exist. Did you install php7.1 properly?

**Comment by mughu-id** [comment]
yes , serverpilot was installed all php version automatically . you should try this serverpilot.io for helping serverpilot users :D , i have done with this , and i want to try install your rep on ubuntu without serverpilot . thank you man

**Comment by alashow** [comment]
I suggest using [Forge](https://forge.laravel.com/) & [Envoyer](https://envoyer.io/). I use it myself for  datmusic-api deployments (only envoyer).
