### ISSUE TITLE
Search results Error

### ISSUE THREAD

**Issue by mughu-id** [alashow/datmusic-api#13]
http://api.apiservice.tk status ok but in search result (http://api.apiservice.tk/search?q=ungu) i have error HttpException in RegistersExceptionHandlers.php line 32:

http://prntscr.com/es96yl

**Comment by alashow** [comment]
You need to set VK accounts in .env file.

**Comment by Carbone13** [comment]
it has been set up with this . and still got error page .

APP_ENV=apiservice
APP_DEBUG=true
APP_KEY=
APP_TIMEZONE=UTC
APP_URL=http://api.apiservice.tk

# setup redis for faster cache
CACHE_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=
REDIS_PORT=6379

# set true to enable basic auth
BASIC_AUTH_ENABLED=false
API_USERNAME=
API_PASSWORD=

# should not contain any spaces, or plus sign
ACCOUNTS=085314019141:085314019141,085314019141:Qcxqxxxx,085314019141:Qcxqxxxx

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

// mp3 files cdn root url. mp3 files will be appended to this url if set
// example: http://sample.cloudfront.net/
CDN_ROOT_URL=

**Comment by mughu-id** [comment]
well , all working now thank you , but how to install datmusic web ?

**Comment by alashow** [comment]
Well, that's the easy part.

Just setup your API endpoint in app.js, minify your app.js to app.min.js or change app.min.js to app.js in index.html, then upload to your webserver.
You can use deploy.sh script upload. Change ssh username, server host, and path your www folder and run it.

**Comment by mughu-id** [comment]
all has been set , but still show network error , thank you . http://apiservice.tk/js/app.min.js?v=2.0.7

http://prntscr.com/esdmj7

**Comment by alashow** [comment]
See console logs to see what's the error.

That's probably the CORS. See config/cors.php

**Comment by mughu-id** [comment]
thank you . work properly .
