### ISSUE TITLE
Need some manual to install a script.

### ISSUE THREAD

**Issue by sakirsa** [alashow/datmusic-api#14]
Hi. Great job! But i have some problems to install and set up a script.

**Comment by alashow** [comment]
Thanks.

See https://github.com/alashow/datmusic-api#deployment

**Comment by sakirsa** [comment]
is it possible to do that script be more dynamic. for example that requests were written down in base and as a result the full music directory was formalized. Add widget to recent requests. The most popular queries and so on. Sitemap. To page fully generated depending on the request. How much would such a job cost?)

**Comment by alashow** [comment]
currently logs are written to storage/logs/datmusic.log. From the log file, you can extract stats like popular queries, most downloaded mp3s, download counts, sitemap etc.
About cost, it depends on a developer.

**Comment by sakirsa** [comment]
hi. how you think, is it possible to parse some music posts from groups/public with dl link

**Comment by alashow** [comment]
Hi, 
I think it's possible but I haven't tried it myself
