### ISSUE TITLE
Page error

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#2]
How do I make the installation on my server?

**Comment by alashow** [comment]
1. Normal Lumen installation
https://lumen.laravel.com/docs/5.3
http://docs.polr.me/en/latest/user-guide/installation/ (project uses Lumen and it has more clear Lumen installation guide)
http://stackoverflow.com/a/37266353/2897341

2. Config
Copy `.env.example` to `.env`edit for your needs.
Edit `config/app.php ` for your needs.
Create symlink from `public/mp3` to `storage/app/public/mp3`

**Comment by mughu-id** [comment]
hello i can't understand with this installation .
