### ISSUE TITLE
ошибки роутинга

### ISSUE THREAD

**Issue by owcedus** [alashow/datmusic-api#24]
http://a40e.owced.com/  - выдает статус 200, все ок

когда пытаюсь сделать поиск:
http://a40e.owced.com/search?q=queen&page=4

выдает ошибки роутинга... в чем может быть проблема ?

**Comment by alashow** [comment]
ty nginx pravilno setup sdelal?

```nginx
location / {
     try_files $uri $uri/ /index.php?$query_string;
}
```

**Comment by owcedus** [comment]
у меня нет доступа к nginx, могу только через .htaccess

**Comment by owcedus** [comment]
все, разобрался. спасибо!
