### ISSUE TITLE
Script execution

### ISSUE THREAD

**Issue by lodem009** [alashow/datmusic-api#25]
Hi, my name is Vlad. My problem execution time script. There is a problem in executing the script, it takes a lot of time to execute, here's an example.
![12358](https://cloud.githubusercontent.com/assets/15075253/26273689/a785cdb0-3d3d-11e7-82d1-3069b5b3bd79.png)

**Comment by alashow** [comment]
Hey. Sorry for late reply. Have you solved this issue?

**Comment by lodem009** [comment]
Yes)
