### ISSUE TITLE
basic_auth

### ISSUE THREAD

**Issue by beqabeqa473** [alashow/datmusic-api#28]
hello.

can you tel me how to get to work basic_auth functionality?

i've enabled it, wrote user:pass but when i'm sending request it doesn't ask for user:pass.

thanks.

**Comment by alashow** [comment]
Hello.

You can enable it by setting `BASIC_AUTH_ENABLED` in .env to `true` then set username and password (`API_USERNAME`, `API_PASSWORD`).

For example:
```yml
BASIC_AUTH_ENABLED=true
API_USERNAME=datmusic
API_PASSWORD=datword
```

**Comment by beqabeqa473** [comment]
it doesn't work.

i've already enabled them.

On 6/6/17, Alashow <notifications@github.com> wrote:
> Closed #28.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/28#event-1111950735


-- 
with best regards beqa

**Comment by alashow** [comment]
I just checked it and it's working.

Are you sure that datmusic can read values from `.env`?

**Comment by beqabeqa473** [comment]
yes, credentials can be read from .env

On 6/6/17, Alashow <notifications@github.com> wrote:
> I just checked it and it's working.
>
> Are you sure that datmusic can read values from `.env`?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/28#issuecomment-306515936


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
so, what can be done to improve the situation?

**Comment by alashow** [comment]
Sorry, I forgot that you also need app environment to be set to `production` or `staging` ([source](https://github.com/alashow/datmusic-api/blob/master/app/Http/Middleware/HttpBasicAuth.php#L29)).

Try setting `APP_ENV` in .env file to `production` (`APP_ENV=production`).

**Comment by beqabeqa473** [comment]
ok, thanks, it worked.

On 6/6/17, Alashow <notifications@github.com> wrote:
> Sorry, I forgot that you also need app environment to be set to `production`
> or `staging`
> ([source](https://github.com/alashow/datmusic-api/blob/master/app/Http/Middleware/HttpBasicAuth.php#L29)).
>
> Try setting `APP_ENV` in .env file to `production` (`APP_ENV=production`).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/28#issuecomment-306575903


-- 
with best regards beqa
