### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by askaFed** [alashow/datmusic-api#30]
Is your API public available? The 502 error occurs when I'm trying to request for example https://api.datmusic.xyz/search

**Comment by alashow** [comment]
No, It's not.

To use datmusic, deploy it to your server: #9

**Comment by beqabeqa473** [comment]
hi.

can you explain please how you did that?

**Comment by syntlyx** [comment]
https://github.com/alashow/datmusic-api/blob/master/config/cors.php#L14

**Comment by beqabeqa473** [comment]
i don't think it is the thing which i've asked.

i think it is for javascript ajax to perform requests from different
servers but only for js

On 12/11/17, Alexandr Sytnyk <notifications@github.com> wrote:
> https://github.com/alashow/datmusic-api/blob/master/config/cors.php#L14
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/30#issuecomment-350782938


-- 
with best regards beqa

**Comment by alashow** [comment]
Yes, it's not cors.
That's just some header validations with nginx.

**Comment by beqabeqa473** [comment]
could you help me please with that?

On 12/12/17, Alashov Berkeli <notifications@github.com> wrote:
> Yes, it's not cors.
> That's just some header validations with nginx.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/30#issuecomment-350899396


-- 
with best regards beqa

**Comment by alashow** [comment]
Try this links to learn more about nginx:
http://nginx.org/en/docs/http/ngx_http_referer_module.html
https://www.nginx.com/resources/wiki/modules/user_agent/
http://nginx.org/en/docs/http/ngx_http_map_module.html
https://www.digitalocean.com/community/tutorials/how-to-use-nginx-s-map-module-on-ubuntu-16-04
https://gist.github.com/kmjones1979/9ada952922e56c78dbceadd614d2df73
https://stackoverflow.com/questions/18970620/nginx-reject-request-if-header-is-not-present-or-wrong
https://stackoverflow.com/questions/18970620/nginx-reject-request-if-header-is-not-present-or-wrong
