### ISSUE TITLE
sometimes 500 Error 

### ISSUE THREAD

**Issue by fgn20** [alashow/datmusic-api#31]
Hi. I'm getting sometimes 500 internal server error. how can I solve?

**Comment by alashow** [comment]
Hi.

You have to look for logs. Log file is located at: `/storage/logs/lumen.log`

**Comment by fgn20** [comment]
Can you check, please? I can't solve.

`[2017-06-17 20:54:07] lumen.ERROR: ErrorException: Undefined offset: 1 in /home/datmusic/api.mydomain.com/current/app/Datmusic/AuthenticatorTrait.php:49
Stack trace:
#0 /home/datmusic/api.mydomain.com/current/app/Datmusic/AuthenticatorTrait.php(49): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined offse...', '/home/datmusic/...', 49, Array)
#1 /home/datmusic/api.mydomain.com/current/app/Datmusic/SearchesTrait.php(22): App\Http\Controllers\ApiController->bootAuthenticator()
#2 /home/datmusic/api.mydomain.com/current/app/Http/Controllers/ApiController.php(21): App\Http\Controllers\ApiController->bootSearches()
#3 [internal function]: App\Http\Controllers\ApiController->__construct()
#4 /home/datmusic/api.mydomain.com/current/vendor/illuminate/container/Container.php(794): ReflectionClass->newInstanceArgs(Array)
#5 /home/datmusic/api.mydomain.com/current/vendor/illuminate/container/Container.php(644): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#6 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Application.php(212): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#7 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(678): Laravel\Lumen\Application->make('App\\Http\\Contro...')
#8 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#9 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#10 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#11 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/datmusic/api.mydomain.com/current/app/Http/Middleware/HttpBasicAuth.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /home/datmusic/api.mydomain.com/current/vendor/illuminate/pipeline/Pipeline.php(137): App\Http\Middleware\HttpBasicAuth->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /home/datmusic/api.mydomain.com/current/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#19 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(529): Laravel\Lumen\Application->handleFoundRoute(Array)
#20 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#21 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /home/datmusic/api.mydomain.com/current/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/datmusic/api.mydomain.com/current/vendor/illuminate/pipeline/Pipeline.php(137): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/datmusic/api.mydomain.com/current/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#29 /home/datmusic/api.mydomain.com/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(476): Laravel\Lumen\Application->dispatch(NULL)
#30 /home/datmusic/api.mydomain.com/current/public/index.php(32): Laravel\Lumen\Application->run()
#31 {main}  `

**Comment by alashow** [comment]
I need to get that indexes safer, but you can solve it by setting proper accounts to your config (to `.env` file or `config/app.php`).
Accounts are separated by comma: `phone:password,phone:password`

**Comment by fgn20** [comment]
yes, i already added some accounts in .env file. when I checked from the site (api.mydomain.com) sometimes im getting "status ok" sometimes 500 internal server error.
I m using only android version. on android 4.4, 5.1, and 7.0 working good but don't working android 6.0. I tried real devices and emulators.

**Comment by alashow** [comment]
You need to check the log only when 500 error is thrown, to get exact exception trace.

**Comment by fgn20** [comment]
Thanks alashow i re checked .env file and i solved 500 Error
Problem `,`
`phone:password,phone:password,`
`phone:password,phone:password`

but i cant solve android 6.0 network error:

`06-17 21:55:30.450 21718-21718/com.m3.app.music W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 21718
06-17 21:55:54.858 21718-23215/com.m3.app.music D/OkHttp: --> GET http://api.mydomain.com/search?q=sa&page=0 http/1.1
06-17 21:55:54.858 21718-23215/com.m3.app.music D/OkHttp: --> END GET
06-17 21:55:54.921 21718-23215/com.m3.app.music D/OkHttp: <-- 404 Not Found http://api.mydomain.com/search?q=sa&page=0 (63ms)
06-17 21:55:54.921 21718-23215/com.m3.app.music D/OkHttp: Server: nginx
06-17 21:55:54.921 21718-23215/com.m3.app.music D/OkHttp: Date: Sat, 17 Jun 2017 21:55:56 GMT
06-17 21:55:54.921 21718-23215/com.m3.app.music D/OkHttp: Content-Type: text/html; charset=iso-8859-1
06-17 21:55:54.921 21718-23215/com.m3.app.music D/OkHttp: Content-Length: 323
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: Connection: keep-alive
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <html><head>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <title>404 Not Found</title>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: </head><body>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <h1>Not Found</h1>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <p>The requested URL /search was not found on this server.</p>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <p>Additionally, a 404 Not Found
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: error was encountered while trying to use an ErrorDocument to handle the request.</p>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: </body></html>
06-17 21:55:54.922 21718-23215/com.m3.app.music D/OkHttp: <-- END HTTP (323-byte body)
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err: android.accounts.NetworkErrorException
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err:     at com.m3.app.music.rest.ResponseHandler.<init>(ResponseHandler.java:42)
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err:     at com.m3.app.music.activities.MainActivity$5$1.<init>(MainActivity.java:327)
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err:     at com.m3.app.music.activities.MainActivity$5.onSuccess(MainActivity.java:327)
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err:     at com.m3.app.music.rest.Summon.onResponse(Summon.java:17)
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
06-17 21:55:54.981 21718-21718/com.m3.app.music W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-17 21:55:54.982 21718-21718/com.m3.app.music W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-17 21:55:54.982 21718-21718/com.m3.app.music W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-17 21:55:54.982 21718-21718/com.m3.app.music W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-17 21:55:54.982 21718-21718/com.m3.app.music W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-17 21:55:54.982 21718-21718/com.m3.app.music W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-17 21:55:54.982 21718-21718/com.m3.app.music W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-17 21:56:00.062 1292-1352/? D/hwcomposer: hw_composer sent 135 syncs in 60s`
