### ISSUE TITLE
API authentication.

### ISSUE THREAD

**Issue by pawmel** [alashow/datmusic-api#33]
Hi, I'm getting 403, how can I fix that?
and, where is api login and api password at VK.com developers website?

**Comment by pawmel** [comment]
this is my env file

APP_ENV=local
APP_DEBUG=true
APP_KEY=
APP_TIMEZONE=UTC
APP_URL=http://localhost.com

# setup redis for faster cache
CACHE_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=
REDIS_PORT=6379

# set true to enable basic auth
BASIC_AUTH_ENABLED=true
API_USERNAME=
API_PASSWORD=

# should not contain any spaces, or plus sign
ACCOUNTS=phone:password,phone:password,phone:password

# vk's mp3 url encoding toggle
DATMUSIC_MP3_URL_DECODER=false

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

// mp3 files cdn root url. mp3 files will be appended to this url if set
// example: http://sample.cloudfront.net/
CDN_ROOT_URL=

**Comment by alashow** [comment]
`ACCOUNTS=phone:password,phone:password,phone:password`
This environment is for VK account phones and passwords.
You are probably getting 403 because of this.

**Comment by pawmel** [comment]
how this param should like like? thanks

**Comment by pawmel** [comment]
ok, worked it out. thanks again!

**Comment by alashow** [comment]
Replace `phone` and `password` with your phone and password. Phone and password separated by `:` and accounts separated by `,`.
