### ISSUE TITLE
What is the reason why some songs are available and other not?

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#35]
I can't find some audio on datmusic demo, why? What is the reason and can I fix it on my own realization on my server?

**Comment by alashow** [comment]
What is the error message?

**Comment by Trabel** [comment]
No error. I am talking about songs, that I am 100% confident is available on vk, but datmusic.xyz can't find them, why?

**Comment by syntlyx** [comment]
Because datmusic uses the European ip when VK needs a Russian ip for more results.

**Comment by Trabel** [comment]
Can I swith it to Russin ip?

**Comment by Trabel** [comment]
If I would deply it on my server?

**Comment by Trabel** [comment]
Oh, my bad, if I will deploy it on server with russion ip, it will give all songs? yes?

**Comment by syntlyx** [comment]
Go to vk with you native IP and then go with russian vpn and see difference

**Comment by Trabel** [comment]
I got difference , but how to fix it? Deply it on russion server?

**Comment by syntlyx** [comment]
You may use russian proxy

**Comment by Trabel** [comment]
Thanks

**Comment by syntlyx** [comment]
Also you may buy vds in veesp.com what i use (STORAGE 1). ping to vk.com 1ms (https://veesp.com/en/products/storage-vps)

**Comment by alashow** [comment]
@Trabel Could you please give me examples? Which What songs you can't find with datmusic.xyz without Russian proxy?

**Comment by Trabel** [comment]
For example song named in vk.com "Дрэ - йк"

**Comment by Trabel** [comment]
Justice - Stress, only remixes, no original song

**Comment by alashow** [comment]
Yes, I can confirm that it's due to the server location. Looks like VK gives good results only to users with Russian IP.

I will try to get some Russian VPS to use as Datmusic's proxy.

**Comment by alashow** [comment]
I enabled proxy if you wanna try out.
https://datmusic.xyz/?q=%D0%94%D1%80%D1%8D%20-%20%D0%B9%D0%BA
https://datmusic.xyz/?q=Justice%20-%20Stress

**Comment by Trabel** [comment]
It works
