### ISSUE TITLE
Hashing by user id instead hashing by search 

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#37]
Is it possible? Every audio on VK has song id and user id (user that has this audio in the playlist), so it is more comfortable to get audio, if you need to get specific audio or audio of specific user.

**Comment by alashow** [comment]
Search id is required to get audio details from cache (URL, title/artist, duration).
I'm hashing queries and page number to get a search id.

**Comment by Trabel** [comment]
got it

**Comment by Trabel** [comment]
But if I have just song id and user id, I can't get the audio, right? There is no way?

**Comment by alashow** [comment]
No.

You can only download an audio if you have already searched, and it's details are in cache.

But you can also find it when it's not in the cache, but you need to have search query and page in. See #32
