### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#39]
I have deplyed datmusic api, and there is no errors, but it still gives 404, what I have to do after deploying? 
Btw, is it okay to use ip of server like domen url in deploying?

**Comment by alashow** [comment]
404 is an error. Enable debugging to see what's wrong and to see where it's failing.

Yes, it's okay to use IP. Just make sure to update APP_URL in .env.

**Comment by Trabel** [comment]
Is this warning important thing when I am trying add-apt-repository ppa:ondrej/php?

WARNING: add-apt-repository is broken with non-UTF-8 locales, see https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

**Comment by alashow** [comment]
Yes, if your system language is non-UTF-8.

See https://github.com/oerdnj/deb.sury.org/issues/56

**Comment by Trabel** [comment]
I redeployed it, now it gives 500 error and log is empty. 
Does this list (https://gist.github.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c) contains Lumen installation? Do I have to to install Lumen?

**Comment by alashow** [comment]
I reckon it's a permission error. Run [fix_permissions.sh ](https://gist.github.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c#file-fix_permissions-sh).

No, you don't have to install. It's the framework.

**Comment by Trabel** [comment]
Yes, you are right, it works! Thanks!
