### ISSUE TITLE
How to change /etc/nginx/sites-available/default

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#40]
How to change /etc/nginx/sites-available/default if I already have there SSL Settings and I can't remove all inside the default. 
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name api.example.com api.example.com;
        return 301 https://$server_name$request_uri;
    }

    server {

    # SSL configuration

    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    include snippets/ssl-api.example.com.conf;
    include snippets/ssl-params.conf;

**Comment by alashow** [comment]
Just remove all lines and change it your nginx config.
