### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#42]
Is it possible to write or rewrite meta tags of mp3?

**Comment by alashow** [comment]
Yes. You can do it after successfully downloading a mp3, [here](https://github.com/alashow/datmusic-api/blob/master/app/Datmusic/DownloaderTrait.php#L350) (add an else statement).

**Comment by Trabel** [comment]
And what is the point when mp3 will download? When I get the link? Or when?

**Comment by alashow** [comment]
Functions are synchronous, i.e API will not serve the mp3 until function finishes it's job.
