### ISSUE TITLE
Download.Fail

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#46]
My log:
August 25, 2017, 4:58 pm, Wisin 0, <ip>
Download.Fail, August 25, 2017, 4:58 pm, 6, <ip>
Why?

**Comment by Trabel** [comment]
You have added installing nodejs, is it reason?

**Comment by alashow** [comment]
To fix: Update datmusic to latest version to include 2bc64323985f3a6a4d06c6abcca325f437ab00af and install nodejs.

VK changed their decoding code. They don't give plain URLs they decode it on browsers with JavaScript. First time when they enabled their encoded URLs, I found PHP version of decoding code from Russian forums (JS translated to PHP). Now I'm just using their JS code with nodejs and call it via CLI to decode URLs.
