### ISSUE TITLE
How does the converting of mp3 bitrate?  

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#5]
It is necessary to install some package or an application on my server so I can be successful with the conversion?

Thank you in advance! And congratulations for this brilliant work.

**Comment by alashow** [comment]
Bitrate conversion is done with ffmpeg.
You can specify ffmpeg binary path in [here](https://github.com/alashow/datmusic-api/blob/master/config/app.php#L58).

Thanks!

**Comment by OoHerbethoO** [comment]
I need to add the directory address complete with the ffmpeg file (ex:/home/xxx/httpfiles/ffmpeg/ffmpeg) or just the ffmpeg file directory?

Sorry my English, I don't speak English!

**Comment by alashow** [comment]
Just install ffmpeg to your server. That should work, without changing anything.
If you install ffmpeg to custom path, specify the path in config file.

**Comment by OoHerbethoO** [comment]
Okay, Thanks!
