### ISSUE TITLE
HttpException  from Guide installation 

### ISSUE THREAD

**Issue by mexekanez** [alashow/datmusic-api#50]
![image](https://user-images.githubusercontent.com/1692609/29994689-5bf3f162-8fde-11e7-8ab9-fa2010387d23.png)

Please help

**Comment by mexekanez** [comment]
trying on heroku and  
aws ec2

**Comment by mexekanez** [comment]
Please provide more clear readme for .env values 
Thanks

**Comment by alashow** [comment]
```bash
# should not contain any spaces, or plus sign
ACCOUNTS=phone:password,phone:password,phone:password
```

Add your VK accounts to `ACCOUNTS`, in `phone:password` format, separated by commas.
Phone number without plus sign or spaces. You can use spaces in password but wrap value in double quotes (`ACCOUNTS="phone:pass word"`).

**Comment by mexekanez** [comment]
thanks @alashow 
general question:
can I get blocked if I will use one account for 10 000 request per day? 

how to scale this ?

**Comment by alashow** [comment]
I don't know whether you will get blocked, but try to use multiple accounts. 

I don't have any specific recommendations for scaling other than using Redis for cache and having large mp3 storage.

**Comment by mexekanez** [comment]
good point, thanks
