### ISSUE TITLE
unavailable.mp3

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [alashow/datmusic-api#52]
Hello, I need your help. Can't understand what goes on, couple days ago everything was good I've received direct links to the tracks, but now for all tracks i got this:

https://m.vk.com/mp3/audio_api_unavailable.mp3?extra=Aev3DM1JrhHMlOGZy3mODdbdm2LMlZnWtdDODMOOy2jHyxbJx3HUvY9notryntq6Cg92EdHZy1f6s3HKDuPHmO9OqKu1mNC4qtvKC29fAvzYzLDyDhmVzdDNn3Dwlu41svnWBtfumuPzAxzmAuOUr3DZz1nZyui2C3u1rwndrKO1vdG3mNvLCK5WwwnOn1vWl25OExP3l2zLqwq2qZfoCgnWrg91p21QCZbtnvzxztvxn2zKmxLhB21czvGUvNCUAveZtu9Vvg0OyZe3puPjnOD1nffNzO5vu3rJsG#CWSYodG

do you know how to fix it? where is a problem?
Thanks!

**Comment by alashow** [comment]
See #34 and #51
