### ISSUE TITLE
Why Json response gives just 19 tracks?

### ISSUE THREAD

**Issue by Trabel** [alashow/datmusic-api#53]
Why Json response gives just 19 tracks and next pages are empty?

**Comment by alashow** [comment]
Maybe there are no more results?
What is the query?

**Comment by Trabel** [comment]
19 tracks whatever the query
Let it be "Foals"

**Comment by syntlyx** [comment]
You should use proxy with Russian ip

**Comment by Trabel** [comment]
Already done, but nothing changed

**Comment by alashow** [comment]
As @sy2nyk suggested, it might be the IP problem.
Are you sure that you are using Russian IP?

**Comment by Trabel** [comment]
![1](https://user-images.githubusercontent.com/30722735/31054632-670baa52-a6bf-11e7-8d7d-1c9a2d846da3.jpg)

**Comment by alashow** [comment]
How can this prove that you are using Russian IP?

Try adding this line to your routes/api.php:
```php
die((string) httpClient()->get("https://ipinfo.io/json")->getBody());
```

Then open your API Url in your browser.

**Comment by alashow** [comment]
Closing for now.

**Comment by Trabel** [comment]
It proves that my server located in Russia and has Russian IP. I have added this line to my routes/api.php, but nothing has changed. 
I have redeployed datmusic api on my server, but nothing has changed too. Any ideas?

**Comment by alashow** [comment]
That line must change something. Does your API work, with 19 tracks, even after adding that line to your api.php?
If yes, you might be adding it to wrong instance of datmusic-api.

**Comment by Trabel** [comment]
Yes, it is still working even after adding. 
I have attached photo of edited api.php
<img width="438" alt="123" src="https://user-images.githubusercontent.com/30722735/31515804-2e06e5c6-af9f-11e7-83b6-d0ed1ff4dac3.PNG">

**Comment by alashow** [comment]
That's kinda "impossible".

Make sure you are adding that line to correct datmusic-api.

**Comment by Trabel** [comment]
My bad, you were right. 
What I've got` "city": "", "region": "St.-Petersburg", "country": "RU",
`

**Comment by alashow** [comment]
Were you testing with wrong deployment?
If that's what you got after adding that line, and if it's still not working on the same server, I don't know why it's not working. Try changing your proxy.

**Comment by Trabel** [comment]
And the most weird thing that it was working on this server well but something rapidly changed without my interrupted or something
