### ISSUE TITLE
Ordering Search Results

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#54]
Good night, how long... lol
I am with a doubt, does it have as I order to show the official songs first and then show these "Karaoke Pro"?
![captura de tela 2017-10-18 as 00 29 53](https://user-images.githubusercontent.com/16544588/31699878-e2853a16-b39b-11e7-94d5-7cff34c5259b.png)

**Comment by alashow** [comment]
You are probably using non-russian IP so VK doesn't give you proper results, only covers & remixes.
See #35 and #49
