### ISSUE TITLE
mp3 url from cache to json

### ISSUE THREAD

**Issue by beqabeqa473** [alashow/datmusic-api#57]
hello.

is it posible to get decodedmp3 url from cache to the json result? or i should movedecoderto parsr?

thanks.

**Comment by alashow** [comment]
Hello.

It's possible. But there is no point in doing that because URLs are bound to IP address. Meaning it's downloadable only by the requester (i.e your server). Your client won't be able to search it.

Why do you need it?

**Comment by beqabeqa473** [comment]
i remember it was possible earlier when mp3 decoding was in search trade.

tell me where to look at it and i will do it for this installation.

On 11/23/17, Alashov Berkeli <notifications@github.com> wrote:
> Hello.
>
> It's possible. But there is no point in doing that because URLs are bound to
> IP address. Meaning it's downloadable only by the requester (i.e your
> server). Your client won't be able to search it.
>
> Why do you need it?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/57#issuecomment-346523731


-- 
with best regards beqa

**Comment by alashow** [comment]
I have changed it in https://github.com/alashow/datmusic-api/commit/96ed1d8e9b48459bb6bb2259b213277388a5c3a1 commit. After that commit, URLs are stored in cache decoded.

**Comment by beqabeqa473** [comment]
i think, some action which will decode url and redirect to decoded url will be good to see

**Comment by alashow** [comment]
I don't understand, what do you mean?

**Comment by beqabeqa473** [comment]
i mean, add route like download which will decode mp3 link on demand
and redirect to this link

On 12/7/17, Alashov Berkeli <notifications@github.com> wrote:
> I don't understand, what do you mean?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/57#issuecomment-349862376


-- 
with best regards beqa

**Comment by alashow** [comment]
Like I said above, that link is unusable by other IPs other than your server's. Because mp3 links are bounded to searchers IP. i.e if you search mp3 from your server, decode link and try to download from your local machine - it won't work.

If you still want this feature, you can add a new route with new function. It's pretty straight forward, if you learn a little bit about Lumen or Laravel. 
In other words, I don't want to add such feature to datmusic-api, because it's useless and compromising.

Cheers.

**Comment by beqabeqa473** [comment]
if i search some tracks with my client, which uses api, mp3 links are
working for the client, which is searching.
i am using pre commit which you mentioned above and everything works.

On 12/7/17, Alashov Berkeli <notifications@github.com> wrote:
> Like I said above, that link is unusable by other IPs other than your
> server. Because mp3 links are bounded to searchers IP. i.e if you search mp3
> from your server, decode link and try to download from your local machine -
> it won't work.
>
> If you still want this feature, you can add a new route with new function.
> It's pretty straight forward, if you learn a little bit about Lumen or
> Laravel.
> In other words, I don't want to add such feature to datmusic-api, because
> it's useless and compromising.
>
> Cheers.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/57#issuecomment-349886777


-- 
with best regards beqa

**Comment by alashow** [comment]
How can you know it works, if before that commit there were no new decoding code (5fd5520feeebbee59d054b83380fcccb27c2c7b4)?

Anyways, here is how you do it:
Add this line to [routes/api.php](https://github.com/alashow/datmusic-api/blob/5fd5520feeebbee59d054b83380fcccb27c2c7b4/routes/api.php#L11)
```php
$app->get('info/{key}/{id}', 'ApiController@info');
```

and add this to [DownloaderTrait](https://github.com/alashow/datmusic-api/blob/5fd5520feeebbee59d054b83380fcccb27c2c7b4/app/Datmusic/DownloaderTrait.php#L40):
```php
public function info($key, $id) {
    return $this->ok($this->getAudio($key, $id));
}
```

**Comment by beqabeqa473** [comment]
i've ported  new decoder to older commit.

On 12/7/17, Alashov Berkeli <notifications@github.com> wrote:
> How can you know it works if before that commit there were no new decoding
> code (5fd5520feeebbee59d054b83380fcccb27c2c7b4)?
>
> Anyways, here is how you do it:
> Add this line to
> [routes/api.php](https://github.com/alashow/datmusic-api/blob/5fd5520feeebbee59d054b83380fcccb27c2c7b4/routes/api.php#L11)
> ```php
> $app->get('info/{key}/{id}', 'ApiController@info');
> ```
>
> and add this to
> [DownloaderTrait](https://github.com/alashow/datmusic-api/blob/5fd5520feeebbee59d054b83380fcccb27c2c7b4/app/Datmusic/DownloaderTrait.php#L40):
> ```php
> public function info($key, $id) {
>     return $this->ok($this->getAudio($key, $id));
> }
> ```
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/57#issuecomment-349908972


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
strange, in older commits, mp3 url was linked to client ip, but now,
really, it is from server

On 12/7/17, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> i've ported  new decoder to older commit.
>
> On 12/7/17, Alashov Berkeli <notifications@github.com> wrote:
>> How can you know it works if before that commit there were no new
>> decoding
>> code (5fd5520feeebbee59d054b83380fcccb27c2c7b4)?
>>
>> Anyways, here is how you do it:
>> Add this line to
>> [routes/api.php](https://github.com/alashow/datmusic-api/blob/5fd5520feeebbee59d054b83380fcccb27c2c7b4/routes/api.php#L11)
>> ```php
>> $app->get('info/{key}/{id}', 'ApiController@info');
>> ```
>>
>> and add this to
>> [DownloaderTrait](https://github.com/alashow/datmusic-api/blob/5fd5520feeebbee59d054b83380fcccb27c2c7b4/app/Datmusic/DownloaderTrait.php#L40):
>> ```php
>> public function info($key, $id) {
>>     return $this->ok($this->getAudio($key, $id));
>> }
>> ```
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/alashow/datmusic-api/issues/57#issuecomment-349908972
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by alashow** [comment]
Do you mean it worked for clients too? Because it was never linked to client IP. VK doesn't know anything about client.

**Comment by beqabeqa473** [comment]
yes, it worked for clients too.

On 12/7/17, Alashov Berkeli <notifications@github.com> wrote:
> Do you mean it worked for clients too? Because it was never linked to client
> IP. VK doesn't know anything about client.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/57#issuecomment-349950847


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
what i did earlier is that i commented unsetting mp3 field in array in
search part, and was getting mp3 field in json.

On 12/7/17, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> yes, it worked for clients too.
>
> On 12/7/17, Alashov Berkeli <notifications@github.com> wrote:
>> Do you mean it worked for clients too? Because it was never linked to
>> client
>> IP. VK doesn't know anything about client.
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/alashow/datmusic-api/issues/57#issuecomment-349950847
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa
