### ISSUE TITLE
Some Searches Getting Error.

### ISSUE THREAD

**Issue by fgn20** [alashow/datmusic-api#58]
Some Searches Getting Error. How can i solve this problem.
my lumen log file.

[2017-11-30 22:00:56] lumen.INFO: Using accounts from .env  
[2017-11-30 22:00:56] lumen.INFO: Using CORS domains from .env  
[2017-11-30 22:00:56] lumen.ERROR: ErrorException: unserialize(): Error at offset 8017 of 8182 bytes in /home/datmusic/mydomain/current/vendor/illuminate/cache/FileStore.php:83
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'unserialize(): ...', '/home/datmusic/...', 83, Array)
#1 /home/datmusic/mydomain/current/vendor/illuminate/cache/FileStore.php(83): unserialize('a:50:{i:0;a:6:{...')
#2 /home/datmusic/mydomain/current/vendor/illuminate/cache/FileStore.php(50): Illuminate\Cache\FileStore->getPayload('query.41a6b434')
#3 /home/datmusic/mydomain/current/vendor/illuminate/cache/Repository.php(129): Illuminate\Cache\FileStore->get('query.41a6b434')
#4 /home/datmusic/mydomain/current/vendor/illuminate/cache/CacheManager.php(301): Illuminate\Cache\Repository->get('query.41a6b434')
#5 /home/datmusic/mydomain/current/vendor/illuminate/support/Facades/Facade.php(237): Illuminate\Cache\CacheManager->__call('get', Array)
#6 /home/datmusic/mydomain/current/app/Datmusic/CachesTrait.php(49): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#7 /home/datmusic/mydomain/current/app/Datmusic/SearchesTrait.php(41): App\Http\Controllers\ApiController->getSearchResult(Object(Illuminate\Http\Request))
#8 [internal function]: App\Http\Controllers\ApiController->search(Object(Illuminate\Http\Request))
#9 /home/datmusic/mydomain/current/vendor/illuminate/container/Container.php(508): call_user_func_array(Array, Array)
#10 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#11 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#12 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ApiController), 'search', Array)
#13 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#14 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#15 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#16 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /home/datmusic/mydomain/current/app/Http/Middleware/HttpBasicAuth.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(137): App\Http\Middleware\HttpBasicAuth->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#24 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(529): Laravel\Lumen\Application->handleFoundRoute(Array)
#25 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#26 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/datmusic/mydomain/current/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(137): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#34 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(476): Laravel\Lumen\Application->dispatch(NULL)
#35 /home/datmusic/mydomain/current/public/index.php(32): Laravel\Lumen\Application->run()
#36 {main}  
[2017-11-30 22:00:58] lumen.INFO: Using accounts from .env  
[2017-11-30 22:00:58] lumen.INFO: Using CORS domains from .env  
[2017-11-30 22:00:58] lumen.ERROR: ErrorException: unserialize(): Error at offset 8017 of 8182 bytes in /home/datmusic/mydomain/current/vendor/illuminate/cache/FileStore.php:83
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'unserialize(): ...', '/home/datmusic/...', 83, Array)
#1 /home/datmusic/mydomain/current/vendor/illuminate/cache/FileStore.php(83): unserialize('a:50:{i:0;a:6:{...')
#2 /home/datmusic/mydomain/current/vendor/illuminate/cache/FileStore.php(50): Illuminate\Cache\FileStore->getPayload('query.41a6b434')
#3 /home/datmusic/mydomain/current/vendor/illuminate/cache/Repository.php(129): Illuminate\Cache\FileStore->get('query.41a6b434')
#4 /home/datmusic/mydomain/current/vendor/illuminate/cache/CacheManager.php(301): Illuminate\Cache\Repository->get('query.41a6b434')
#5 /home/datmusic/mydomain/current/vendor/illuminate/support/Facades/Facade.php(237): Illuminate\Cache\CacheManager->__call('get', Array)
#6 /home/datmusic/mydomain/current/app/Datmusic/CachesTrait.php(49): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#7 /home/datmusic/mydomain/current/app/Datmusic/SearchesTrait.php(41): App\Http\Controllers\ApiController->getSearchResult(Object(Illuminate\Http\Request))
#8 [internal function]: App\Http\Controllers\ApiController->search(Object(Illuminate\Http\Request))
#9 /home/datmusic/mydomain/current/vendor/illuminate/container/Container.php(508): call_user_func_array(Array, Array)
#10 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#11 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#12 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ApiController), 'search', Array)
#13 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#14 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#15 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#16 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /home/datmusic/mydomain/current/app/Http/Middleware/HttpBasicAuth.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(137): App\Http\Middleware\HttpBasicAuth->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#24 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(529): Laravel\Lumen\Application->handleFoundRoute(Array)
#25 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#26 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/datmusic/mydomain/current/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(137): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /home/datmusic/mydomain/current/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#34 /home/datmusic/mydomain/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(476): Laravel\Lumen\Application->dispatch(NULL)
#35 /home/datmusic/mydomain/current/public/index.php(32): Laravel\Lumen\Application->run()
#36 {main}  
[2017-11-30 22:01:01] lumen.INFO: Using accounts from .env  
[2017-11-30 22:01:01] lumen.INFO: Using CORS domains from .env

**Comment by alashow** [comment]
Try cleaning your cache

**Comment by fgn20** [comment]
Solved, Thanks.
