### ISSUE TITLE
How many request until Captcha is asked?

### ISSUE THREAD

**Issue by Sam2790** [alashow/datmusic-api#59]
Hello, sorry for creating an Issue as this is not one. I want to use your datmusic-api, but I want to know how many mp3's I can download per day before my accounts gets limited? And Lets say if I have 10 Accounts and it switches to another when the first one is limited, is it a problem that the user has the same IP?

Thank you very much
PS: alashow I wrote you an Email and also in Insta, this is my last hope to get an answer

**Comment by alashow** [comment]
Hello,

I did not receive any captchas yet, so I wouldn't know about it.
Yes, if VK starts to ask you captchas, I think, it will be linked to both user and IP address.

Besides, you should not expect datmusic-api to work in long-term, as VK is starting to introduce their new music service.
