### ISSUE TITLE
ITunes API

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#6]
Hi, here I am again (lol).
Could you explain to me how do I integrate the iTunes API in research?
Because I would like to get the data that was returned by iTunes (https://itunes.apple.com/search?term=) and add in myapi.com/search ...

I tried adding changing the file "HttpClient.php", but not got success, only an error (400 = Bad Request). Thank you, I love your work you are to be congratulated!
![captura de tela 2017-02-16 as 03 35 25](https://cloud.githubusercontent.com/assets/16544588/23010227/030be964-f3f9-11e6-86a6-802edec61c59.png)

**Comment by alashow** [comment]
I don't know why it returns bad request error.

But I suggest using this: https://github.com/ijanerik/PHP-iTunes-API

**Comment by OoHerbethoO** [comment]
![captura de tela 2017-02-16 as 13 21 54](https://cloud.githubusercontent.com/assets/16544588/23029958/fbc79656-f44a-11e6-93cc-47260f7bb321.png)
The script json data but return this error, what might be going on?

**Comment by alashow** [comment]
VK is enabling protection for their site.

**Comment by OoHerbethoO** [comment]
to circumvent or remove this protection from the VK? What do I do now :/

**Comment by alashow** [comment]
I don't know yet :)

datmusic itself is working now, are you using latest datmusic?

**Comment by OoHerbethoO** [comment]
Yes, I'm using the latest ...

**Comment by OoHerbethoO** [comment]
I think they removed the link mp3 files of "input" on m.vk.com. I created a new account and tested it on other computers and that the same thing within the site vk.com. I'm sending my screen capture.
![captura de tela 2017-02-16 as 17 40 13](https://cloud.githubusercontent.com/assets/16544588/23040155/057fa192-f46f-11e6-9304-8465644d5699.png)

**Comment by alashow** [comment]
I know what happened. I just don't have any solution yet.

**Comment by alashow** [comment]
it's back working again fda2e04c8f6ad1cbae060f5bef686facaa09dab4

**Comment by OoHerbethoO** [comment]
Thacks! 🥇 💯
