### ISSUE TITLE
video streams in some files

### ISSUE THREAD

**Issue by beqabeqa473** [alashow/datmusic-api#60]
hello.

i am developing music streaming service and there is a strict check for valid mp3.
some files from vk have video streams inside.

could you please add possibility to extract clean mp3 from these files before serving file to client

it is
        exec("$ffmpegPath -i $input -vn -acodec copy $output", $exOutput,
            $result);

thanks.

**Comment by alashow** [comment]
Hi,

This is out of datmusic's scope. Feel free to fork and implement it yourself.
I don't want to add extra step for processing before downloading an mp3.

Cheers.

**Comment by beqabeqa473** [comment]
yes, but this type of mp3 might not play in some specific environment.

On 12/28/17, Alashov Berkeli <notifications@github.com> wrote:
> Closed #60.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alashow/datmusic-api/issues/60#event-1403845542


-- 
with best regards beqa

**Comment by alashow** [comment]
I have never seen mp3 like that, so that shouldn't be a big problem.
