### ISSUE TITLE
Json_decode error: Syntax error

### ISSUE THREAD

**Issue by Quarx2k** [alashow/datmusic-api#62]
Hello, everything worked until today.
Now it always throw this error:
> in /datmusic/current/vendor/guzzlehttp/guzzle/src/functions.php line 302
> at GuzzleHttp\json_decode('[]"Name":"remixmid","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixsid6","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixgid","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixemail","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixpass","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixapi_sid","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixpermit","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-Age":null,"Expires":1,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"remixat","Value":"DELETED","Domain":".vk.com","Path":"\/","Max-
> 
> 
I checked generated json and it really looks like incorrect.
What can be a problem? Thanks.

**Comment by syntlyx** [comment]
Remove cookie file from storage folder

**Comment by Quarx2k** [comment]
It was easy :)
Works now. Thanks!

**Comment by alashow** [comment]
I also encountered this exception a while ago, didn't investigate. Might be related to "multi-threaded" file writes or something simpler.
