### ISSUE TITLE
“Not found” on every search, even after last update

### ISSUE THREAD

**Issue by kostyakoz** [alashow/datmusic-api#65]
![screen shot 2018-04-10 at 20 43 47](https://user-images.githubusercontent.com/1935229/38573869-fd87c37c-3cff-11e8-80a5-029725649d09.png)

Got empty dict `[]` when trying to find anything. Autorizated successfully.

**Comment by alashow** [comment]
This is probably the end for the current implementation of datmusic-api. Vk started showing errors like "you repeated this action too much", captchas etc..

**Comment by alashow** [comment]
Last commits have nothing to do with it.

**Comment by kostyakoz** [comment]
But I see it’s works fine on https://datmusic.xyz

**Comment by ilcham** [comment]
i got same problem.

**Comment by alashow** [comment]
I currently attached datmusic deployment to some other api, which is, imho, uses vk's official apps' keys.

I will wait for now until that stops to work, then probably try to avoid "same action" error if possible and then add support for captchas (i.e return error with captcha, allow user to type it,  send back captcha answer to vk, just like in old datmusic).
Or just find the official keys and use the api directly.

**Comment by alashow** [comment]
https://github.com/alashow/datmusic-api/tree/ya-api

**Comment by alashow** [comment]
https://github.com/alashow/datmusic-api/tree/vk-api

**Comment by alashow** [comment]
Both branches work perfectly now.
