### ISSUE TITLE
New branch tests, readme updates

### ISSUE THREAD

**Issue by alashow** [alashow/datmusic-api#67]
After #65, I added 2 new branches that work. [ya-api](https://github.com/alashow/datmusic-api/tree/ya-api) and [vk-api](https://github.com/alashow/datmusic-api/tree/vk-api)

It would be great if someone would test them and help me with README's.

**Comment by kostyakoz** [comment]
I've just upgraded to `ya-api` branch, and entered my key.

Whats wrong?
![screen shot 2018-04-18 at 10 21 42](https://user-images.githubusercontent.com/1935229/38917110-614e2282-42f2-11e8-8e22-ae4ca93922ff.png)

**Comment by alashow** [comment]
Not sure, but looks like ya-api not responding proper json.
Replace [this line](https://github.com/alashow/datmusic-api/blob/a26f1312f56ed83c40e9f38bcaba08d2bc5589cc/app/Datmusic/ParserTrait.php#L31) with this to debug:
```php
dd((string) $response->getBody());
```

**Comment by kostyakoz** [comment]
Now that says `string(6) "no key"`
But both `.env` and `config/app.php` contains key 🤔

**Comment by ilcham** [comment]
you need ubuntu 19.02

**Comment by alashow** [comment]
Did you find what's the problem? @kostyakoz

**Comment by kostyakoz** [comment]
@alashow no, still has same error.

**Comment by sy2nyk** [comment]
![image](https://user-images.githubusercontent.com/2834652/39134924-75a9e946-4720-11e8-976a-c9fbbb9ebc70.png)
was it anyone?

**Comment by wapmastera** [comment]
everything works fine for me. Is it possible to get only one result by **source_id** ? or results by **genre_id** ?
