### ISSUE TITLE
I have problems implementing the Api for stream and download

### ISSUE THREAD

**Issue by krrskl** [alashow/datmusic-api#69]
It turns out that when I try to stream or download from my local directory (running the api with PHP) it does not allow me to access the .mp3 files and those that it manages to download after a few minutes of being the error [image 1] drops them to 0 byte, I would like to receive some instructions from those who are using the api without problems, thanks.

![image](https://user-images.githubusercontent.com/16052364/41027098-d1604220-693b-11e8-922e-12a387263876.png)
![image](https://user-images.githubusercontent.com/16052364/41027148-e1790b74-693b-11e8-9b11-6ac4c7403385.png)

**Comment by syntlyx** [comment]
`ln -s storage/app/public/mp3 public/mp3`

**Comment by krrskl** [comment]
![image](https://user-images.githubusercontent.com/16052364/41254718-eac40d76-6d89-11e8-84a3-93835265bc20.png)
Result

**Comment by krrskl** [comment]
It is mandatory to have an aws account ?

**Comment by syntlyx** [comment]
https://gist.github.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c

**Comment by krrskl** [comment]
Thanks, I have run the commands such and as they appear in that documentation, now I get a different error and it has to do with the authentication of VK, and I do not understand why it is thrown if I already indicated my token in the .env

![image](https://user-images.githubusercontent.com/16052364/41257104-537546e4-6d91-11e8-8d4b-b1274595e559.png)

I executed this command after finishing with the fix_permissions.sh ` ~/api.example.com/current $ php -S localhost:8000 -t public/`

**Comment by syntlyx** [comment]
invalid access_token

**Comment by syntlyx** [comment]
try to use ya-api. low cost price and no more problems

**Comment by krrskl** [comment]
You refer to using this: https://www.npmjs.com/package/ya-api ??

**Comment by syntlyx** [comment]
https://github.com/alashow/datmusic-api/tree/ya-api

**Comment by syntlyx** [comment]
I wrote api to another website. there are no restrictions on captcha and requests. maybe I'll put it on github soon

**Comment by krrskl** [comment]
Thank you very much for your kind help, I hope that update.

**Comment by marcorochadev** [comment]
@sy2nyk 

Can you share your new API? thank you so much.

another question. I was able to do everything right, the downlod is working, but it always lowers the same audio file. sounds like an API protection audio

I understand what I mean

**Comment by krrskl** [comment]
@marcorochadev 

Greetings, did you have any problems when setting up the project? Any of the ones that showed up did you come up ?? Thank you, I have not yet given it to work for me.

**Comment by marcorochadev** [comment]
@krrskl97 send me ur whatsapp to talk about this API. i help u and u helpme.

marcorocha.dev@gmail.com
