### ISSUE TITLE
Call to undefined method ErrorException::getStatusCode() 

### ISSUE THREAD

**Issue by raver1975** [alashow/datmusic-api#7]
I'm not sure how to get past this error:
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method ErrorException::getStatusCode() 

$ php -S localhost:8000 -t public
PHP 7.1.2 Development Server started at Sat Mar  4 10:32:04 2017
Listening on http://localhost:8000
Document root is C:\Users\Paul\Desktop\datmusic-api-master\public
Press Ctrl-C to quit.
[Sat Mar  4 10:32:08 2017] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method ErrorException::getStatusCod
e() in C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\fde922e6cc3ccf07661bc930efe5322e7b6d3f8d.php:3
Stack trace:
#0 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\Engines\PhpEngine.php(42): include()
#1 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\Users\\Pa
ul\\D...', Array)
#2 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\Users\\Paul\\D...', Array)
#3 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\af84f4e88b546a33b44bc in C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\fd
e922e6cc3ccf07661bc930efe5322e7b6d3f8d.php on line 3
[Sat Mar  4 10:32:08 2017] ::1:49946 [500]: / - Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method ErrorException::getStatus
Code() in C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\fde922e6cc3ccf07661bc930efe5322e7b6d3f8d.php:3
Stack trace:
#0 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\Engines\PhpEngine.php(42): include()
#1 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\Users\\Pa
ul\\D...', Array)
#2 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\Users\\Paul\\D...', Array)
#3 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\af84f4e88b546a33b44bc in C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\fd
e922e6cc3ccf07661bc930efe5322e7b6d3f8d.php on line 3
[Sat Mar  4 10:32:08 2017] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Symfony\Component\Debug\Exce
ption\FatalErrorException::getStatusCode() in C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\fde922e6cc3ccf07661bc930efe5322e7b6d3f8d.php:3
Stack trace:
#0 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\Engines\PhpEngine.php(42): include()
#1 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\Users\\Pa
ul\\D...', Array)
#2 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\Users\\Paul\\D...', Array)
#3 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\Users\Paul\Desktop\datmusic-api-master\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\Users\Paul\Desktop\datmusic-api-master\storag in C:\Users\Paul\Desktop\datmusic-api-master\storage\framework\views\fde922e6cc3ccf07661bc930efe5322e7b6d3f8d.
php on line 3

**Comment by alashow** [comment]
Non http exception was throwing and I was trying to get a status code of it.

The last commit solves that issue, but not your real issue. You need to enable debugging by setting true in the `.env` file (APP_DEBUG) and investigate it.

You can re-open this issue and post the real stacktrace so we can help you.
