### ISSUE TITLE
Audio_api_unavailable.mp3 datMusic-Api

### ISSUE THREAD

**Issue by krrskl** [alashow/datmusic-api#71]
Greetings, I've tried several tokens to see what happens that does not let me download or listen to music, because I jump to this audio.
`"url": "https://vk.com/mp3/audio_api_unavailable.mp3"`

**Comment by marcorochadev** [comment]
please help us

**Comment by krrskl** [comment]
The answer when downloading or listening is the Audio is available on vk.com and in official VKontakte applications

**Comment by divyamsingh234** [comment]
You can try  Russian proxy or VPN. It might fix your problem @krrskl97 .

**Comment by krrskl** [comment]
@divyamsingh234  Thanks for the data, I'll try it that way.
