### ISSUE TITLE
Obtaining VK tokens automatically

### ISSUE THREAD

**Issue by vodka2** [alashow/datmusic-api#72]
Just FYI I found a way to get VK tokens automatically or using a rooted Android device. No installation of VK apps required, but it may be necessary to intercept Android Checkin request when using AVD (not sure about that). More info here (in russian): https://github.com/vodka2/vk-audio-token . It would be great if you add this feature to your repo.

**Comment by alashow** [comment]
That's great!
Will link it in readme later after testing it.
It would be great if you included English translation to your repo though.
Thanks.

**Comment by vodka2** [comment]
@alashow Ok, I've translated it to English.

**Comment by alashow** [comment]
Great work man! I checked it out and seems like it's working.
I guess the only problem is getting `str24` more easily if the current one stops working.

Updated Readme with a link to the repo.

**Comment by vodka2** [comment]
I think it would be better to leave the original method of getting tokens too, if my code stops working. Btw have you managed to get another `str24`? If not I can send you some via email for testing. Note that not all `str24` strings work.

**Comment by alashow** [comment]
Last time I checked KateMobile enabled ssl pinning, so it was obsolete anyways.

No I didn't, I don't have rooted device at this time (1st option) and I didn't get the second one.

**Comment by vodka2** [comment]
This is strange, I've just downloaded the latest version (50.2 lite) from apkpure and was able to view the received token using Charles. Getting audio URIs also works.

**Comment by alashow** [comment]
They might have disabled it later then. Will add it back if your method stops working.
