### ISSUE TITLE
Amazon Cloud Drive upload

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#8]
Hello, could you add the function to upload to Amazon Cloud Drive? I think it would be really interesting! Thank you.

**Comment by alashow** [comment]
Upload to Amazon Cloud Drive (ACD)? Like, using ACD instead of S3? Or adding option so user can download music to his/her ACD account?

**Comment by OoHerbethoO** [comment]
Use ACD instead of S3, S3 is too expensive and charge for PULL and GET request. My idea is that the files to be uploaded to my account of the ACD instead of S3.

**Comment by alashow** [comment]
I agree that S3 is too expensive (you can use CloudFront to reduce traffic bills though).
Unfortunately, I don't have time and resources for implementing ACD support.
I will accept a good PR for implementing better support for ACD or Google Storage.

I moved datmusic to a dedicated server (Hetzner), which has storage box support (~$7/month for 1TB, + cron script to clean old mp3s).

**Comment by OoHerbethoO** [comment]
Okay, thanks!
