### ISSUE TITLE
I can't download mp3s

### ISSUE THREAD

**Issue by Zakirzhan** [alashow/datmusic-api#80]
I can't download/stream mp3s via generated urls
<img width="1042" alt="Снимок экрана 2020-08-24 в 20 22 57" src="https://user-images.githubusercontent.com/15848416/91063605-a693ec00-e647-11ea-8b44-4235d44adc87.png">
file datmusic.log
<img width="465" alt="Снимок экрана 2020-08-24 в 20 24 50" src="https://user-images.githubusercontent.com/15848416/91063804-df33c580-e647-11ea-86d2-1e7eb14c6158.png">
How can I fix this problem?

**Comment by alashow** [comment]
Check why curl can't download by debugging what happens [here](https://github.com/alashow/datmusic-api/blob/941ad5dc8a92d138dbe2ebd7d49627b903c99ca4/app/Datmusic/DownloaderTrait.php#L285).

**Comment by LevanQerdikashvili** [comment]
hello, i have simillar problem.

how can solve it ? 
:(
![image](https://user-images.githubusercontent.com/70694064/92153131-d3f54c80-ee34-11ea-94a8-b16d6449afb3.png)


search working.
img url working
stream and download not working.

**Comment by alashow** [comment]
Check my previous comment. The stacktrace doesn't give any information about why it's failing.

**Comment by LevanQerdikashvili** [comment]
I cann't fix this problem. please help me

when file saved  example 
![image](https://user-images.githubusercontent.com/70694064/92208138-a394c900-ee9b-11ea-8f4a-5ad9ee29d69b.png)
it's  0  byte.
and 

![image](https://user-images.githubusercontent.com/70694064/92209383-f2436280-ee9d-11ea-8f20-f7d070669d8f.png)

why not returned mp3 url? is this problem ?

**Comment by alashow** [comment]
How does a mp3 url look like? Or rather just send a var dump of `$item`>

**Comment by LevanQerdikashvili** [comment]
https://imus.ge/search?q=eminem&page=1

I added item in search

![image](https://user-images.githubusercontent.com/70694064/92210476-d17c0c80-ee9f-11ea-8b4e-de10cdc8056d.png)

**Comment by alashow** [comment]
Okay, so urls seems to be empty. No good. Vk might be using new protection
or something. What user agent are you using and how old are your tokens?

**Comment by LevanQerdikashvili** [comment]
for tokkens I used this 
https://vkhost.github.io/    (VK ADMIN)
![image](https://user-images.githubusercontent.com/70694064/92211211-23716200-eea1-11ea-9954-31f676bc7ea5.png)


user agent default (I have not changed anything)




![image](https://user-images.githubusercontent.com/70694064/92211339-5f0c2c00-eea1-11ea-8906-5ea6f08779c2.png)

**Comment by alashow** [comment]
Try using a token by clicking Kate mobile in there, as that's the default
user agent set in here:
https://github.com/alashow/datmusic-api/blob/941ad5dc8a92d138dbe2ebd7d49627b903c99ca4/app/Util/HttpClient.php#L47

Also, did you have a lot of files in mp3 cache? As you might need to move
them to new folder based path.

**Comment by LevanQerdikashvili** [comment]
when I used kate mobile key
result is : {"status":"error","error":{"message":"Token confirmation required","code":25}}

**Comment by LevanQerdikashvili** [comment]
mp3 cache time now 1 secconds for testing.

**Comment by alashow** [comment]
I mention that error in readme file

**Comment by LevanQerdikashvili** [comment]
ok. I believe everything will be fine :))))

**Comment by alashow** [comment]
https://qna.habr.com/q/631865 here someone says it says that when you put
wrong user agent. Maybe they used different kate mobile version or something

**Comment by LevanQerdikashvili** [comment]
oooh yess :) working  mp3 url.

but :D

dl and stream no.

https://api.imus.ge//dl/774fc0aa/884768df

**Comment by alashow** [comment]
Dump the mp3 url where it fails to download with 404 or something. It's probably empty URLs again. Did you match tokens with correct user agents?

**Comment by LevanQerdikashvili** [comment]
problem was tokken and not user agent. 
now I used for tokken
https://vkserv.ru/api/inst/token

VK.ME (kate not working)

now mp3 urls  working but  dl and stream not working (I am trying to solve this).

**Comment by alashow** [comment]
> now mp3 urls working but dl and stream not working (I am trying to solve this).

mp3 URLs working and dl/stream not working doesn't make sense. Try [this](https://github.com/alashow/datmusic-api/issues/80#issuecomment-679832673)

**Comment by alashow** [comment]
I updated the code to use newer API and now I use VK Android-s tokens.

**Comment by LevanQerdikashvili** [comment]
@alashow  
1) can I find audio via ID? ( I want to create page example   example.com/eminem/beautiful )
2) can I find similar audio files by genres or audio ID? 
3) can I find  lyrics?

**Comment by LevanQerdikashvili** [comment]
@alashow 

how can solve it ? 

![image](https://user-images.githubusercontent.com/70694064/93013660-91154080-f5bb-11ea-9874-5bc34b45f1b6.png)

**Comment by alashow** [comment]
Check the readme file about captchas.

**Comment by LevanQerdikashvili** [comment]
@alashow 
I try this 
https://site.com/search?q=eminem&captcha_index=1&captcha_id=949738714471&captcha_key=hqx2
and 
https://site.com/search?q=eminem&captcha_index=1&captcha_id=949738714471&captcha_key=https://api.vk.com/captcha.php?sid=988974952549&s=1

but not working

**Comment by alashow** [comment]
Captcha resolution should work correctly if you type the correct captcha key. The first one is correct, you need to submit the guessed captcha key, not the URL to it.
