### ISSUE TITLE
Shows same result for every request

### ISSUE THREAD

**Issue by bosit777** [alashow/datmusic-api#83]
array (
  'status' => 'ok',
  'data' => 
  array (
    0 => 
    array (
      'id' => 'dfa55476',
      'source_id' => '100_1',
      'artist' => 'и в официальных приложениях ВКонтакте',
      'title' => 'Аудио доступно на ',
      'duration' => 25,
      'date' => 1481906888,
      'key' => '4d384af7',
      'download' => 'http://vultr.qorovul.space/dl/4d384af7/dfa55476',
      'stream' => 'http://vultr.qorovul.space/stream/4d384af7/dfa55476',
      'cover' => 'http://vultr.qorovul.space/cover/4d384af7/dfa55476',
    ),
  ),
)

**Comment by alashow** [comment]
Wrong token or you're not using the same user agent.

**Comment by bosit777** [comment]
Where should i set user agent?

**Comment by alashow** [comment]
https://github.com/alashow/datmusic-api/blob/200ee7f0c3264b5f5d807505df384af93ca69e8b/app/Util/HttpClient.php#L47
