### ISSUE TITLE
Installation tutorial test

### ISSUE THREAD

**Issue by alashow** [alashow/datmusic-api#9]
I created installation tutorial gist here: https://gist.github.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c

Can someone help me to test it? By following instructions.

Thanks :)

**Comment by Porco-Rosso** [comment]
Following the instructions I run into this:
<img width="970" alt="screen shot 2017-05-10 at 9 37 14 pm" src="https://cloud.githubusercontent.com/assets/7024527/25917631/04d49126-35c9-11e7-85b9-ead6a5850891.png">

I believe the problem has to do with the .env configuration. 
Could you be more verbose about what needs to go where?
In particular, what goes in APP_KEY and ACCOUNTS ?

````APP_ENV=local
APP_DEBUG=true
APP_KEY=
APP_TIMEZONE=UTC
APP_URL=http://localhost.com

# setup redis for faster cache
CACHE_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=
REDIS_PORT=6379

# set true to enable basic auth
BASIC_AUTH_ENABLED=false
API_USERNAME=
API_PASSWORD=

# should not contain any spaces, or plus sign
ACCOUNTS=phone:phone,phone:password,phone:password

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

// mp3 files cdn root url. mp3 files will be appended to this url if set
// example: http://sample.cloudfront.net/
CDN_ROOT_URL=````

**Comment by Porco-Rosso** [comment]
Nevermind, stupid mistake: I forgot the country code, since you said no plus sign.
Can confirm working. As for the guide, you should add a note to change the permissions script for your own user.

**Comment by alashow** [comment]
Could you please elaborate on your note?
```bash
chown -R datmusic:www-data storage .env
```
You mean I should add a note to change `datmusic` to `myuser`?
If yes, in the whole guide I assume that user will be using `datmusic` username, so I thought that shouldn't be a problem.

**Comment by Porco-Rosso** [comment]
My confusion stems from the fact that in all the commands that must be typed/copy-pasted it is clear that the user must be changed. However, when downloading the script, there is no mention that it must be altered. Indeed the wget line auto-executes, resulting in an error with no indication that it was because it must be edited first.
`wget https://gist.githubusercontent.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c/raw/fix_permissions.sh -O - | sh`

**Comment by alashow** [comment]
I see.

I added a note before fix_permissions section.
