### ISSUE TITLE
Getting 500 Error (Search Audio) & Download.Fail.InvalidAudio

### ISSUE THREAD

**Issue by Josiahhenry23** [alashow/datmusic-api#92]
I have installed this new system on my server due to the old systems being depreciated.
I have updated my Tokens, Implemented Proxy with Socks5, and changed the UserAgent to be aligned with my token, but the system will not download music or allow for search.

I am starting to think the client might not be getting set.

<img width="1536" alt="Screen Shot 2021-11-13 at 3 37 56 PM" src="https://user-images.githubusercontent.com/20512525/141659747-48766726-663e-4e78-a3b0-40fb7ba35747.png">

**Comment by Josiahhenry23** [comment]
And on a regular search, I get a 404 not found.

**Comment by alashow** [comment]
VK has changed their way of encoding urls, we can't decode it to mp3 URLs no more https://github.com/alashow/datmusic-api/blob/df7c96bedf640e3ce6f0f562525729e68b57974a/app/Datmusic/ParserTrait.php#L42-L54

**Comment by Josiahhenry23** [comment]
So does that mean the use of this api is no more?

**Comment by alashow** [comment]
Welp, at least until a new solution is found. I might fallback to Deemix api until then (https://github.com/alashow/datmusic-api/tree/deemix + https://gist.github.com/alashow/15978818a82cb4a85e765dc348ce463e).
